### ISSUE TITLE
 Error: Could not connect to the stack. Please check your credentials.

### ISSUE THREAD

**Issue by Malith077** [Contentstack-Solutions/contentstack-cli-tsgen#2]
I have double checked all the api keys and region, but it is unable to connect to my stack.  

Currently using EU region
    Error: Could not connect to the stack. Please check your credentials.

**Comment by okkevandereijk** [comment]
@Malith077 Is there any update on this issue? Thanks in advance!

**Comment by Malith077** [comment]
> @Malith077 Is there any update on this issue? Thanks in advance!

it still doesn't work, so I gave up contentstack since theres no reply from these people.

**Comment by wszerad** [comment]
I have the same issue :cry:

**Comment by Malith077** [comment]
> I have the same issue 😢

Try contentful, almost the same CMS but better support than contentstack.

**Comment by abhinav-from-contentstack** [comment]
@Malith077 @wszerad  Hi, sorry about the late reply. We have fixed this issue in version 1.0.7. Could you please check it again.

**Comment by abhinav-from-contentstack** [comment]
Hi @wszerad  @Malith077, aplologies for the late reply. We have found the issue and will be releasing a fix shortly.

**Comment by shafeeqd959** [comment]
Hi @Malith077 @wszerad @okkevandereijk , We have released the new version (1.0.10) which includes the fix for this issue. Please update the plugin from your end. Thanks

**Comment by wszerad** [comment]
@shafeeqd959 Thanks, new version is working well
