### ISSUE TITLE
Add support for Branches

### ISSUE THREAD

**Issue by ChristopherJennings** [Contentstack-Solutions/contentstack-cli-tsgen#23]
Per @NunoMCP's comment on #20, we need to add support for branches with this plugin.

**Comment by cdjjrufin** [comment]
Any update for when this will be implemented?

**Comment by netrajpatel** [comment]
Hi @cdjjrufin,
Branches support is added in the TSGen plugin, Please install the latest TSGen plugin and try this feature.
I'm closing this ticket now.

Thank You!
