### ISSUE TITLE
Syntax error when generating types

### ISSUE THREAD

**Issue by itsTyd** [Contentstack-Solutions/contentstack-cli-tsgen#30]
Hi!

I'm trying to generate types for the Stack, but when I run the tsgen it returns the following Syntax error:
```SyntaxError: '=>' expected.```

>  reference: ()[];
| ^

Let me know if you need more information!

**Comment by netrajpatel** [comment]
Hi @itsTyd,
It seems the issue has been fixed in recent releases.
Can you please install the latest version of this plugin and try it?

**Comment by itsTyd** [comment]
Hi @netrajpatel just updated and ran it, it's working fine now! Thank you!!
