### ISSUE TITLE
Why generated types don't contain UID and other meta data?

### ISSUE THREAD

**Issue by max-cross** [Contentstack-Solutions/contentstack-cli-tsgen#63]
If you fetch entries via SDK or API it sends entries with additional data like UID, created_at, publish_details fields, and so on. But the TSGen plugin doesn't add this information when you generate types.

**Comment by StanislavFedyna** [comment]
the same problem :(

**Comment by abhinav-from-contentstack** [comment]
Hi @max-cross @StanislavFedyna, we have added a new flag `--include-system-fields` to address this problem. Please use it while generating types, and types for fields like `created_at`, `publish_details` should be generated.

**Comment by max-cross** [comment]
> Hi @max-cross @StanislavFedyna, we have added a new flag `--include-system-fields` to address this problem. Please use it while generating types, and types for fields like `created_at`, `publish_details` should be generated.

Thanks 👍

**Comment by StanislavFedyna** [comment]
> Hi @max-cross @StanislavFedyna, we have added a new flag `--include-system-fields` to address this problem. Please use it while generating types, and types for fields like `created_at`, `publish_details` should be generated.|

That's what our team needs, thanks!
