### ISSUE TITLE
Wrong types for references

### ISSUE THREAD

**Issue by max-cross** [Contentstack-Solutions/contentstack-cli-tsgen#64]
CS always sends references as an array of entries. It means that all references must be like arrays, and empty arrays in case if reference is not specified. Even if this field is not mandatory, it will be an empty array. 
```
{
  someEntryReference: EntryModel[]
}
```

But for some reason TSGen gives you:
```
{
  someEntryReference?: EntryModel
}
```
Looks like a bug or not documented behavior.

**Comment by sgoess** [comment]
This was probably introduced with v2.1.8 because of this https://github.com/Contentstack-Solutions/contentstack-cli-tsgen/issues/43 - I also think this is a bug and needs a rollback.

**Comment by sgoess** [comment]
This is finally solved with current release https://github.com/Contentstack-Solutions/contentstack-cli-tsgen/releases/tag/v2.2.2
