### ISSUE TITLE
Type Error for empty Date and Select Fields

### ISSUE THREAD

**Issue by sgoess** [Contentstack-Solutions/contentstack-cli-tsgen#66]
I have a content model with two non-mandatory fields of type Date and Select. The tsgen plugin exports this content model as follows:

```TSX
export interface TestModel {
  title: string;
  date?: string;
  select?: "lorem" | "ipsum";
}
```

However, this is what is actually sent from the API with the two non-optional fields left empty (generic fields removed from output):

```JSON
{
    "date": null,
    "select": null,
    "title": "Test TSGen",
}
```

This causes a TS error: `Type 'null' is not assignable to type 'string | undefined'`.

**Comment by AniketDev7** [comment]
Hi @sgoess  
We have released fix for this issue. Install latest tsgen version 2.2.1 to get the fix.
