### ISSUE TITLE
Generated typings do not name refrences correctly

### ISSUE THREAD

**Issue by olafurns7** [Contentstack-Solutions/contentstack-cli-tsgen#8]
Content stack appends **Connection** after all field names that are references, and also adds subfields in GraphQL.

example:

Content type field:

Reference to ContentBelt type

GraphQL request response:

`"content_beltsConnection": {
            "edges": [
              {
                "node": {
                  "title": "Collapsibles test",
                  "system": {
                    "uid": "blt847f4e37080902a8"
                  }
                }
              },]
}`

however the tsgen result of that is just the field name, with an array of the content type:

`navigation_menu: ContentBelt[]`

**Comment by aman19K** [comment]
Hey @olafurns7 ,Support for graphQL has been added to tsgen plugin. Install the most recent version, please.
**Example:-** csdx tsgen -a "delivery token alias" -o "contentstack/generated.d.ts" --api-type graphql
**Doc for reference:-** https://www.contentstack.com/docs/developers/cli/tsgen-plugin
**PR:-** #82
