### ISSUE TITLE
GraphQL dependency missing when using rest as API type

### ISSUE THREAD

**Issue by simoneldevig** [Contentstack-Solutions/contentstack-cli-tsgen#93]
# GraphQL dependency missing when using rest as API type

After the release of `2.3.0` it broke our codegen as `grapql` is missing even though we're not using GraphQL.

`(node:25983) [MODULE_NOT_FOUND] ModuleLoadError Plugin: contentstack-cli-tsgen: [MODULE_NOT_FOUND] require failed to load /Users/user/.local/share/@contentstack/cli/node_modules/contentstack-cli-tsgen/lib/commands/tsgen.js: Cannot find module 'graphql'`

**Comment by AniketDev7** [comment]
Hi @simoneldevig 
We were able to replicate this at our end and have fixed it and released latest version 2.3.1
Can u try by installing this once at ur end ?

**Comment by simoneldevig** [comment]
@AniketDev7 yes, it works.

Thanks!
